# Generated by Django 2.0.7 on 2018-09-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户')),
                ('goods_id', models.CharField(max_length=50, verbose_name='商品ID')),
                ('goods_url', models.CharField(max_length=255, verbose_name='商品地址')),
                ('order_sn', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='评价内容')),
                ('over', models.CharField(blank=True, default='是', max_length=50, null=True, verbose_name='是否完结订单')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '我的评价',
                'verbose_name_plural': '我的评价',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户')),
                ('orderno', models.CharField(max_length=50, unique=True, verbose_name='己方订单号')),
                ('order_sn', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='订单金额')),
                ('order_type', models.CharField(max_length=50, verbose_name='订单类型')),
                ('pay_url', models.CharField(max_length=50, verbose_name='付款链接')),
                ('status', models.CharField(max_length=50, verbose_name='订单状态')),
                ('evalute', models.CharField(blank=True, default='否', max_length=50, null=True, verbose_name='是否已评价')),
                ('create_date', models.DateTimeField(verbose_name='创建日期')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '我的订单',
                'verbose_name_plural': '我的订单',
            },
        ),
        migrations.CreateModel(
            name='Orderdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='金额')),
                ('token', models.CharField(max_length=255, verbose_name='通讯令牌')),
                ('goods_url', models.CharField(max_length=255, verbose_name='商品地址')),
                ('goods_number', models.IntegerField(verbose_name='商品数量')),
                ('orderno', models.CharField(max_length=50, unique=True, verbose_name='己方订单号')),
                ('notifyurl', models.CharField(max_length=255, verbose_name='回调地址')),
                ('sign', models.CharField(max_length=50, verbose_name='签名')),
                ('order', models.CharField(blank=True, default='否', max_length=50, null=True, verbose_name='是否已提交订单')),
                ('goods_id', models.CharField(blank=True, default='', max_length=50, verbose_name='商品ID')),
                ('callbackurl', models.CharField(blank=True, default='', max_length=50, verbose_name='回调')),
                ('extends', models.CharField(blank=True, default='', max_length=50, verbose_name='扩展字段')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '我的下单',
                'verbose_name_plural': '我的下单',
            },
        ),
    ]
