# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='over',
            field=models.CharField(blank=True, default='是', max_length=50, null=True, verbose_name='是否完结订单'),
        ),
        migrations.AlterField(
            model_name='order',
            name='evalute',
            field=models.CharField(blank=True, default='否', max_length=50, null=True, verbose_name='是否已评价'),
        ),
        migrations.AlterField(
            model_name='orderdown',
            name='order',
            field=models.CharField(blank=True, default='否', max_length=50, null=True, verbose_name='是否已提交订单'),
        ),
    ]
