# Generated by Django 2.0.7 on 2018-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdd', '0003_auto_20180907_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_url',
            field=models.CharField(max_length=255, verbose_name='付款链接'),
        ),
    ]
