# Generated by Django 2.0.7 on 2018-09-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdd', '0004_auto_20180907_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_url',
            field=models.TextField(verbose_name='付款链接'),
        ),
    ]
