# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20180830_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='linenos',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
